# Generated by Django 2.2.3 on 2019-07-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avataar',
            field=models.ImageField(default='default_user.png', upload_to='profile_pics'),
        ),
    ]
