# Generated by Django 2.2.3 on 2019-07-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_avataar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avataar',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
