# Generated by Django 2.2.3 on 2019-08-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190731_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avataar',
            field=models.ImageField(default='default_user.png', upload_to='profile_pics'),
        ),
    ]
