# Generated by Django 2.2.3 on 2019-08-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_answers',
            field=models.BooleanField(default=False),
        ),
    ]
