# Generated by Django 2.2.3 on 2019-08-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djora', '0002_question_has_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Publihsed')], default='draft', max_length=10),
        ),
    ]
