# Generated by Django 2.2.3 on 2019-08-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djora', '0003_auto_20190801_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
